### ISSUE TITLE
Additional timing utilities 

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/sorunlib#169]
I'd like a more readable way to call this sort of code 
```
scan_stop = datetime.datetime(2024, 9, 21, 21, 15, 24, tzinfo=datetime.timezone.utc)
if datetime.datetime.now(tz=UTC) < scan_stop - datetime.timedelta(minutes=10):
    all the stuff
```

and 

```
scan_start = datetime.datetime(2024, 9, 22, 7, 13, 34, 416664, tzinfo=datetime.timezone.utc)
scan_stop = datetime.datetime(2024, 9, 22, 8, 42, 16, 343049, tzinfo=datetime.timezone.utc)
if now > scan_start:
    # adjust scan parameters
    az = 399.672 + -0.00386*(now-scan_start).total_seconds()
else: 
    az = 399.672
if now > scan_stop:
    # too late, don't scan
    pass
else:
    run.acu.move_to(az, 48.1)
```

We have these basically everywhere throughout the schedules. I propose `run.is_after( time, tolerance=None )` and `run.is_before(time, tolerance=None)` these should return Booleans.

**Comment by BrianJKoopman** [comment]
Thanks for the suggestion! I have some questions/comments as I'm thinking about the implementation here.

## `run.is_before()`
> ```python
> scan_stop = datetime.datetime(2024, 9, 21, 21, 15, 24, tzinfo=datetime.timezone.utc)
> if datetime.datetime.now(tz=UTC) < scan_stop - datetime.timedelta(minutes=10):
>     all the stuff
> ```

Just to check -- you're picturing something like this:
```python
if run.is_before('2024-09-21T21:15:24+00:00', tolerance=10):
    # all the stuff
```

Is `# all the stuff` ever more than just a `seq.scan()` followed by a `run.smurf.bias_step()`?

Checking whether we have enough time to actually do a worthwhile scan feels like it could be incorporated into `seq.scan()` with a "minimum duration" parameter. But then we still need to handle optionally running any post-scan operations, like bias steps.

## `run.is_after()`
> ```python
> scan_start = datetime.datetime(2024, 9, 22, 7, 13, 34, 416664, tzinfo=datetime.timezone.utc)
> scan_stop = datetime.datetime(2024, 9, 22, 8, 42, 16, 343049, tzinfo=datetime.timezone.utc)
> if now > scan_start:
>     # adjust scan parameters
>     az = 399.672 + -0.00386*(now-scan_start).total_seconds()
> else: 
>     az = 399.672
> if now > scan_stop:
>     # too late, don't scan
>     pass
> else:
>     run.acu.move_to(az, 48.1)
> ```

This is checking if it's after `scan_start` but before `scan_stop`, so I'm not sure if I like `run.is_after()` for a name. To me this looks like a modified `acu.move_to()`.

The details related to the scan parameters, i.e. `399.672` and `-0.00386` here, are different each scan, so they'll need to be parameters that get passed to whatever this function is.

This might look something like:
```python
run.acu.move_to_target(az, el, start_time, stop_time, drift)
```

Which in practice would look like:
```python
run.acu.move_to_target(399.672, 48.1, 
    start_time='2024-09-22T07:13:34.416664+00:00', 
    stop_time='2024-09-22T08:42:16.343049+00:00',
    drift=-0.00386)
```

This maybe doesn't even need to be a new function, we can just add these new optional arguments to the existing `acu.move_to()` to account for target drift?

**Comment by kmharrington** [comment]
Discussion on DAQ call! Yes we like move_to_target and just adding a minimum duration to seq.scan is a good step here.
