### ISSUE TITLE
[Discussion] Effective range of the wire grid operation

### ISSUE THREAD

**Issue by hnakata-JP** [simonsobs/sorunlib#188]
In the group Slack discussion, I got a request about the effective range of the wire grid. Within the standard operation, coordinators want to include el=48. The question is

- Can we cover elevation = [48,52] with the wire grid operation?

**Comment by BrianJKoopman** [comment]
Covering wider range is fine by me, and is a simple enough change. The spec here came in part from the Gridloader procedure document that @sadachi5 wrote up. 

A couple of questions:
* Can the hardware handle running at lower elevation? 
* Is the 52 deg upper cutoff necessary? Or is running up to 90 fine? (We currently don't have this upper limit check in place.)

**Comment by sadachi5** [comment]
Current implementation checks just el > 50 deg.
I'm OK with changing it to el > 48 deg.

**Comment by sadachi5** [comment]
I made pull-request for it.
