### ISSUE TITLE
Expand Options for Scan definition

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/sorunlib#71]
Looking at the function here:

https://sorunlib.readthedocs.io/en/latest/_modules/sorunlib/seq.html#scan 

I know at a minimum that we're going to be testing scan speed and acceleration profiles during commissioning. And we'll need to be able to specify these at a minimum. Can we expose every parameter possible through this function so we'll have them available to the scheduler and/or to hand edited schedules?

**Comment by BrianJKoopman** [comment]
For my own future reference, the new [`set_scan_params()`](https://socs.readthedocs.io/en/main/agents/acu_agent.html#socs.agents.acu.agent.ACUAgent.set_scan_params) task in the ACU Agent should be used for this.
