### ISSUE TITLE
Implement boresight commands for SAT

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/sorunlib#73]
Adding to the list of things: I have noticed that boresight positions aren't in the "move to" command. 

EDIT: Co-rotator feature request split to #76.

**Comment by BrianJKoopman** [comment]
> These will also need to be different for the LAT and SAT.

Thanks, Katie. How do these differ between the platforms? The ACU agent is common and has a single [`set_boresight()` command](https://socs.readthedocs.io/en/main/agents/acu_agent.html#socs.agents.acu.agent.ACUAgent.set_boresight), which I think might control the 3rd axis in either case.

**Comment by kmharrington** [comment]
Oh interesting that the commands are the same. Optically they'll be fairly different since the co-rotator isn't exactly a boresight rotation. I would imagine for the LAT we'd want functions that did `move_to(az, el, corotate=True)` and then an option to move the co-rotator independently. For the SAT the boresight really is a third axis and the use-case is more `move_to(az, el, bore)`
